[package]
name = "hello"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.15"
termion = "1.5"
failure = "0.1"
rand = "0.8"
unicode-width = "0.1.*"